### ISSUE TITLE
Bot doesn't seem to make proper line-breaks

### ISSUE THREAD

**Issue by Andre601** [dessant/label-actions#1]
What do I have to make in order for the bot to make proper line-breaks?

Right now I have set this text here in the `label-actions.yml` as a response for the `Problem: Need more info` label:
https://github.com/Andre601/PurrBot/blob/master/.github/label-actions.yml#L27-L35

But it seems like that the bot completely ignores new lines and just puts everything in a single line.
Here's the response in a test-issue:
https://github.com/Andre601/PurrBot/issues/10#issuecomment-457350033

I tried it with adding double-spaces in case it's an issue with markdown, but this doesn't fix it.
But empty lines seems the bot to recognize.

**Image**
![image](https://user-images.githubusercontent.com/11576465/51707728-39127a80-2022-11e9-8a26-6d06205abe5d.png)

**Comment by dessant** [comment]
Leave two lines empty, like this:

yaml
```
actions:
  "Type: Support request":
    comment: >
      First paragraph.  
      
      
      Second paragraph.
```

This is a handy guide for YAML: https://learnxinyminutes.com/docs/yaml/

**Comment by Andre601** [comment]
Why using `>` then?

In my opinion would it be better to go with `|` or `|-` to make it recognize new lines right from the start (talking about the template).
Are there any benefits of using `>` over the other methods?

**Comment by dessant** [comment]
`>` is used if you want to add line breaks within a paragraph in your config file, without messing up formatting in the GitHub comment. You can use `|`, but then keep paragraphs on a single line, because line breaks within the paragraph will also be preserved in the comment. It's entirely up to you, use the syntax you prefer the most for a specific use case. :yum:
